/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA;
typedef struct tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ;
typedef struct tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__89azkb4JUGfhEDamui6ufig tySequence__89azkb4JUGfhEDamui6ufig;
typedef struct tySequence__89azkb4JUGfhEDamui6ufig_Content tySequence__89azkb4JUGfhEDamui6ufig_Content;
typedef struct tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ;
typedef struct tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw;
typedef struct tyTuple__ZiSL9aqBTKXK9b9buyxeDR9b6Q tyTuple__ZiSL9aqBTKXK9b9buyxeDR9b6Q;
typedef struct tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg;
typedef struct tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA;
typedef struct tyObject_ArithmeticDefect__aMy29brWPSjGP5fnvmg24Rg tyObject_ArithmeticDefect__aMy29brWPSjGP5fnvmg24Rg;
typedef struct tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__89azkb4JUGfhEDamui6ufig {
  NI len; tySequence__89azkb4JUGfhEDamui6ufig_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__89azkb4JUGfhEDamui6ufig trace;
	Exception* up;
};
struct tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw {
	Exception Sup;
};
struct tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA {
	tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw Sup;
};
struct tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw {
	NI len;
	NI cap;
	tyTuple__ZiSL9aqBTKXK9b9buyxeDR9b6Q* d;
};
struct tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ {
	tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw traceStack;
	tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg {
	tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw Sup;
};
struct tyObject_ArithmeticDefect__aMy29brWPSjGP5fnvmg24Rg {
	tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw Sup;
};
struct tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA {
	tyObject_ArithmeticDefect__aMy29brWPSjGP5fnvmg24Rg Sup;
};
struct tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__89azkb4JUGfhEDamui6ufig_Content { NI cap; tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4704)(tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3528)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ* s_p1, TNimTypeV2* desc_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u74)(tySequence__89azkb4JUGfhEDamui6ufig dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4716)(tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3019)(tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4773)(tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4785)(tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5177)(tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5189)(tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__9c4PFdzSb6f6iS8eaDhvLZA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__AZEPCycOV30yR2LweMemkg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__DiQqKYu2t14eQ9cRhHPgScA_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4429;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 3053828096, 2210756352};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9c4PFdzSb6f6iS8eaDhvLZA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u4716, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 3053828096, 2433682176};
N_LIB_PRIVATE TNimTypeV2 NTIv2__AZEPCycOV30yR2LweMemkg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u60, .size = sizeof(tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___system_u4785, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[5] = {3701606400, 1285336064, 3053828096, 3434543616, 606742784};
N_LIB_PRIVATE TNimTypeV2 NTIv2__DiQqKYu2t14eQ9cRhHPgScA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___system_u5189, .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4429);
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_FALSE;
	{
		tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
LA6_: ;
		rememberCycle__system_u3528(result, cell_1, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4704)(tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4704(((tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__TzI3paKQY09cLjc9cmCvur3A_4;
{	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u3019(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__TzI3paKQY09cLjc9cmCvur3A_4)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_4);
	}BeforeRet_: ;
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	p_1 = ((void**) (q_p0));
	{
		tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		j_1 = ((tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ*) (env_p1));
		add__system_u3011((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4716)(tyObject_RangeDefect__9c4PFdzSb6f6iS8eaDhvLZA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4773)(tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4773(((tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4785)(tyObject_IndexDefect__AZEPCycOV30yR2LweMemkg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5177)(tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5177(((tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5189)(tyObject_OverflowDefect__DiQqKYu2t14eQ9cRhHPgScA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
